### ISSUE TITLE
enviroment variable for database-configuration

### ISSUE THREAD

**Issue by henfri** [QuantumObject/docker-mywebsql#6]
Hello,

thanks for this container!
I would like to make it easier for users to use this in conjunction with my service built with docker-compose.
Thus I would like to pass the database server and credentials.

Currently my docker-compose looks like this:

```
editor:
  image: quantumobject/docker-mywebsql
  ports:
   - 8088:80
  links:
   - database


database:
  image: mysql:5.7
  volumes:
   - "/srv/Daten/dockerconfig/uvr/db/:/var/lib/mysql"
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: mypass
   MYSQL_DATABASE: uvr1611
   MYSQL_USER: myuser
   MYSQL_PASSWORD: uvr1611
```

When logging into mywebsql I need to select the database and credentials. With enviroment-variables I could avoid that.
Could you easily add such an option?

Regards,
Hendrik
